services:
  nodejs:
    # restart: always
    build: .
    ports:
      - 4000:4000
    environment:
      - MONGO_URI=mongodb://db:27017/healthcheck
    depends_on:
      db:
        condition: service_healthy


  db:
    image: mongo
    ports:
      - 27018:27017
    hostname: dbx
    volumes:
      - data:/data/db
      - config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 5s
      retries: 5


  mongo-express:
      image: mongo-express
      ports:
        - 8082:8081
      depends_on:
        db:
          condition: service_healthy
      environment:
        # - ME_CONFIG_OPTIONS_EDITORTHEME=db
        - ME_CONFIG_MONGODB_URL=mongodb://db:27017/healthcheck
        - ME_CONFIG_MONGODB_SERVER=db
        # - ME_CONFIG_MONGODB_PORT=27017
      #   - VCAP_APP_PORT=8082
      #   - ME_CONFIG_MONGODB_ENABLE_ADMIN=TRUE
      #   - VCAP_APP_HOST=localhost
      restart: unless-stopped
      
  
volumes:
  data:
  config:
